# GitHub Sponsors configuration
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [y-zahidi]
custom:
  - "https://y-zahidi.github.io"
